TRUNCATE TABLE [util].Num

;WITH
L1 AS(SELECT 1 AS C UNION ALL SELECT 1 AS O),
L2 AS(SELECT 1 AS C FROM L1 AS A CROSS JOIN L1 AS B), 
L3 AS(SELECT 1 AS C FROM L2 AS A CROSS JOIN L2 AS B),
L4 AS(SELECT 1 AS C FROM L3 AS A CROSS JOIN L3 AS B),
L5 AS(SELECT 1 AS C FROM L4 AS A CROSS JOIN L4 AS B),
L6 AS(SELECT 1 AS C FROM L5 AS A CROSS JOIN L5 AS B),
Nums AS(SELECT ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS N FROM L5)

INSERT INTO [util].[Num]
SELECT TOP 10000 N FROM Nums ORDER BY N

